# Generated by Django 3.0.7 on 2020-06-25 13:45

from django.db import migrations, models
import eventapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20200625_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eventapp.models.event_image_upload_location, verbose_name='image'),
        ),
    ]
