# Generated by Django 3.0.7 on 2020-06-26 02:43

from django.db import migrations, models
import django.db.models.deletion
import eventapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200625_1051'),
        ('eventapp', '0003_eventcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='capcity',
            new_name='capacity',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authapp.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eventapp.models.event_category_image_upload_location, verbose_name='image'),
        ),
    ]
