# Generated by Django 3.0.7 on 2020-06-27 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20200626_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(256)], verbose_name='address'),
        ),
    ]
