# Generated by Django 3.0.6 on 2020-06-07 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200608_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', code='invalide_phone_number', message='Invalide phone number')], verbose_name='phone number'),
        ),
    ]
